php:
  build: Docker/php/
  ports:
    - 8123:80
  links:
    - mysql
  volumes:
    - ./Source:/var/www/html
  env_file:
    - docker-env.yml

mysql:
  build: Docker/mysql/
  env_file:
    - docker-env.yml
varnish:
  build: Docker/varnish
  links:
    - php
  ports:
    - 8181:80
  env_file:
    - docker-env.yml
